# Generated by Django 5.1.4 on 2026-10-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_alter_candidature_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='engagements',
            field=models.JSONField(blank=True, default=list, verbose_name="Souhaits d'engagement"),
        ),
        migrations.AddField(
            model_name='candidature',
            name='volunteer_poles',
            field=models.JSONField(blank=True, default=list, verbose_name='Pôles (bénévolat)'),
        ),
    ]
