# Generated by Django 5.2.17 on 2026-10-03 17:24

import apps.common.validators
import apps.memberships.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_candidature_engagements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=apps.memberships.models._cv_storage, upload_to='candidatures_cv/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.common.validators.MaxFileSizeValidator(10)], verbose_name='CV'),
        ),
    ]
