# Generated by Django 5.1.4 on 2026-10-03 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='is_outstanding',
            field=models.BooleanField(default=False, verbose_name='Travail remarquable'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='points_awarded',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Points accordés'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='return_reason',
            field=models.TextField(blank=True, verbose_name='Motif du renvoi'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='size',
            field=models.CharField(choices=[('small', 'Petite'), ('medium', 'Moyenne'), ('large', 'Grande')], default='medium', max_length=10, verbose_name='Envergure'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='submission_note',
            field=models.TextField(blank=True, verbose_name='Note de soumission'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Soumise le'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validée le'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('submitted', 'À valider'), ('done', 'Validée'), ('blocked', 'Bloquée')], default='todo', max_length=20),
        ),
    ]
