# Generated by Django 5.1.4 on 2026-10-03 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0005_departmenttask_is_outstanding_and_more'),
        ('projects', '0003_projecttask_is_outstanding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_label', models.CharField(max_length=100, verbose_name='Période')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='À remplir avant le')),
                ('status', models.CharField(choices=[('pending', 'À remplir'), ('submitted', 'À confirmer'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('self_scores', models.JSONField(blank=True, default=dict)),
                ('improve_self', models.TextField(blank=True, verbose_name='Ce que je peux améliorer')),
                ('department_help', models.TextField(blank=True, verbose_name='Ce que le département peut faire')),
                ('remark', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('final_scores', models.JSONField(blank=True, default=dict)),
                ('feedback', models.TextField(blank=True, verbose_name='Retour du responsable')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='departments.department')),
                ('launched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Point d'étape",
                'verbose_name_plural': "Points d'étape",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('month', 'Membre du mois'), ('year', "Membre de l'année")], max_length=10)),
                ('period_start', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distinction',
                'verbose_name_plural': 'Distinctions',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'period_start'), name='one_award_per_period')],
            },
        ),
        migrations.CreateModel(
            name='PointEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField()),
                ('source', models.CharField(choices=[('task', 'Tâche validée'), ('checkin', "Point d'étape"), ('adjustment', 'Ajustement')], max_length=20)),
                ('label', models.CharField(max_length=300)),
                ('on_time', models.BooleanField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, verbose_name='Motif (ajustement)')),
                ('awarded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='engagement.checkin')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='departments.department')),
                ('department_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='departments.departmenttask')),
                ('project_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projecttask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attribution de points',
                'verbose_name_plural': 'Registre des points',
                'ordering': ['-awarded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('department_task__isnull', False)), fields=('department_task',), name='points_once_per_department_task'), models.UniqueConstraint(condition=models.Q(('project_task__isnull', False)), fields=('project_task',), name='points_once_per_project_task'), models.UniqueConstraint(condition=models.Q(('checkin__isnull', False)), fields=('checkin',), name='points_once_per_checkin')],
            },
        ),
    ]
