# Generated by Django 5.1.4 on 2026-10-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Mois évalué'),
        ),
    ]
