# Generated by Django 5.1.4 on 2026-10-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_checkin_period_start'),
        ('payments', '0002_contribution_cashentry_contributionmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointentry',
            name='contribution_month',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_entry', to='payments.contributionmonth'),
        ),
        migrations.AlterField(
            model_name='pointentry',
            name='source',
            field=models.CharField(choices=[('task', 'Tâche validée'), ('checkin', "Point d'étape"), ('adjustment', 'Ajustement'), ('contribution', 'Cotisation')], max_length=20),
        ),
    ]
