# Generated by Django 5.2.17 on 2026-10-03 17:24

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(8)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='recap_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/recap/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(8)], verbose_name='Image récapitulative'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='events/speakers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(8)]),
        ),
    ]
