# Generated by Django 5.2.17 on 2026-10-09 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmailCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Compteur d'emails du jour",
            },
        ),
        migrations.CreateModel(
            name='MemberEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Objet')),
                ('body', models.TextField(verbose_name='Message (HTML nettoyé)')),
                ('template', models.CharField(blank=True, max_length=30, verbose_name='Modèle')),
                ('cta_label', models.CharField(blank=True, max_length=60, verbose_name='Texte du bouton')),
                ('cta_url', models.URLField(blank=True, verbose_name='Lien du bouton')),
                ('audience', models.CharField(choices=[('selection', 'Membres choisis'), ('all', 'Tous les membres actifs'), ('bureau', 'Bureau'), ('leads', 'Responsables de département'), ('department', 'Un département')], max_length=20, verbose_name='Destinataires')),
                ('audience_label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
            ],
            options={
                'verbose_name': 'Email aux membres',
                'verbose_name_plural': 'Emails aux membres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec')], default='pending', max_length=10)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='mailing.memberemail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destinataire',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
