# Generated by Django 5.2.17 on 2026-10-10 01:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Abonné')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(default='site', max_length=30, verbose_name='Origine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Désinscrit le')),
            ],
            options={
                'verbose_name': 'Abonné à la newsletter',
                'verbose_name_plural': 'Abonnés à la newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='memberemail',
            name='audience',
            field=models.CharField(choices=[('selection', 'Membres choisis'), ('all', 'Tous les membres actifs'), ('bureau', 'Bureau'), ('leads', 'Responsables de département'), ('department', 'Un département'), ('newsletter', 'Abonnés à la newsletter')], max_length=20, verbose_name='Destinataires'),
        ),
    ]
