# Generated by Django 5.2.17 on 2026-10-09 21:10

from django.db import migrations, models

# Reprise des accès qui étaient automatiques avant la Gestion des accès par section :
# chacun garde ce qu'il avait ; ensuite, seul l'admin accorde ou retire.
BUREAU = ["events", "members", "departments", "news", "ranking"]


def grant_current_access(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(poste__isnull=False).exclude(role__in=["admin", "visiteur", "candidat"]):
        sections = list(BUREAU)
        if user.poste in ("tresorier", "tresorier_adj"):
            sections.append("treasury")
        if user.poste == "president":
            sections.append("applications")
        user.sections = sections
        user.save(update_fields=["sections"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text="Sections de gestion accordées par l'admin (voir SECTIONS).", verbose_name='Sections accordées'),
        ),
        migrations.RunPython(grant_current_access, migrations.RunPython.noop),
    ]
