# Generated by Django 5.2.17 on 2026-10-04 14:31

import apps.common.validators
import apps.members.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_memberprofile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=apps.members.models._cv_storage, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.common.validators.MaxFileSizeValidator(10)]),
        ),
    ]
