# Generated by Django 5.2.17 on 2026-10-09 22:08

from django.db import migrations, models


def hide_all_profiles(apps, schema_editor):
    """Aucun membre n'avait choisi d'apparaître sur le site : tous les profils sont
    masqués ; chacun le réactive lui-même dans Mon profil (invitation par email :
    commande invite_public_profiles)."""
    apps.get_model("members", "MemberProfile").objects.update(is_public=False)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_memberprofile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='public_invite_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Invitation à rendre le profil public envoyée le'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Profil public'),
        ),
        migrations.RunPython(hide_all_profiles, migrations.RunPython.noop),
    ]
