# Generated by Django 5.2.17 on 2026-10-09 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_departmenttask_is_outstanding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='project_managers',
            field=models.ManyToManyField(blank=True, related_name='managed_project_departments', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaires de projets'),
        ),
    ]
