# Generated by Django 5.1.4 on 2026-10-03 10:17

import apps.payments.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(verbose_name='Premier mois couvert')),
                ('months', models.PositiveSmallIntegerField(verbose_name='Nombre de mois')),
                ('monthly_rate', models.PositiveIntegerField(verbose_name='Tarif mensuel (FCFA)')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('paid_on', models.DateField(verbose_name='Date du paiement')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('transfer', 'Virement'), ('other', 'Autre')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotisation',
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense')], max_length=10)),
                ('category', models.CharField(choices=[('contributions', 'Cotisations'), ('donations', 'Dons'), ('sponsorship', 'Sponsoring'), ('events_income', 'Événements (recettes)'), ('other_income', 'Autre recette'), ('events', 'Événements'), ('communication', 'Communication'), ('tools', 'Outils & abonnements'), ('logistics', 'Logistique'), ('other_expense', 'Autre dépense')], max_length=30)),
                ('label', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('transfer', 'Virement'), ('other', 'Autre')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, storage=apps.payments.models._attachment_storage, upload_to='treasury/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='Justificatif')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contribution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_entry', to='payments.contribution')),
            ],
            options={
                'verbose_name': 'Écriture de caisse',
                'verbose_name_plural': 'Journal de caisse',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('rate', models.PositiveIntegerField()),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_months', to='payments.contribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month'],
                'constraints': [models.UniqueConstraint(fields=('user', 'month'), name='contribution_once_per_month')],
            },
        ),
    ]
