# Generated by Django 5.1.4 on 2026-10-03 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_contribution_cashentry_contributionmonth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rappel de cotisation',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(verbose_name='Premier mois déclaré')),
                ('months', models.PositiveSmallIntegerField(default=1)),
                ('monthly_rate', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('transfer', 'Virement'), ('other', 'Autre')], default='mobile_money', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('proof', models.ImageField(upload_to='payment_proofs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Preuve de paiement')),
                ('status', models.CharField(choices=[('pending', 'À valider'), ('approved', 'Validée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contribution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaration', to='payments.contribution')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Déclaration de paiement',
                'verbose_name_plural': 'Déclarations de paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
