# Generated by Django 5.2.17 on 2026-10-03 17:24

import apps.common.validators
import apps.payments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_contributionreminder_paymentdeclaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=apps.payments.models._attachment_storage, upload_to='treasury/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), apps.common.validators.MaxFileSizeValidator(10)], verbose_name='Justificatif'),
        ),
        migrations.AlterField(
            model_name='paymentdeclaration',
            name='proof',
            field=models.ImageField(upload_to='payment_proofs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='Preuve de paiement'),
        ),
    ]
