# Generated by Django 5.2.17 on 2026-10-04 14:31

import apps.common.validators
import apps.payments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_cashentry_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdeclaration',
            name='proof',
            field=models.ImageField(storage=apps.payments.models._proof_storage, upload_to='payment_proofs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='Preuve de paiement'),
        ),
    ]
